### ISSUE TITLE
Love the app however, it never joins a room

### ISSUE THREAD

**Issue by bluenevus** [maalaang/Sunrise#20]
I went to the demo and it says 

"Connecting...
Cannot join the room. Retry to join this room or create a new room."

No matter how many retries or creating new rooms, it never actually connects to the room.  Furthermore, if you share the link for someone to join, their video is not seen.  So I created a login hoping that would solve the issue however, it doesn't change anything expect having my name in the block automatically.  joining a room and having other join the room doesn't work.

Any insight?

**Comment by bluenevus** [comment]
also, clicking the plus to invite someone doesn't work in the demo either

**Comment by kyeongwan** [comment]
Sorry, we opened server again now. The server had been closing abnormally.
